# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_PyLogin(object):
    def setupUi(self, PyLogin):
        PyLogin.setObjectName(_fromUtf8("PyLogin"))
        PyLogin.resize(1025, 738)
        PyLogin.setMinimumSize(QtCore.QSize(1025, 738))
        PyLogin.setMaximumSize(QtCore.QSize(1025, 738))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/AppleLogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PyLogin.setWindowIcon(icon)
        self.label = QtGui.QLabel(PyLogin)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 751))
        self.label.setMinimumSize(QtCore.QSize(1041, 751))
        self.label.setMaximumSize(QtCore.QSize(1041, 751))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayoutWidget = QtGui.QWidget(PyLogin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 110, 111, 101))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(PyLogin)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 110, 241, 101))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.user_name = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet(_fromUtf8("color: #e3e4e5;"))
        self.user_name.setObjectName(_fromUtf8("user_name"))
        self.verticalLayout_2.addWidget(self.user_name)
        self.phone_name = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.phone_name.setFont(font)
        self.phone_name.setStyleSheet(_fromUtf8("color: #e3e4e5;"))
        self.phone_name.setObjectName(_fromUtf8("phone_name"))
        self.verticalLayout_2.addWidget(self.phone_name)
        self.label_4 = QtGui.QLabel(PyLogin)
        self.label_4.setGeometry(QtCore.QRect(-210, -240, 351, 461))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(PyLogin)
        self.label_6.setGeometry(QtCore.QRect(520, 90, 71, 131))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 120, 331, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.battery_status = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.battery_status.setFont(font)
        self.battery_status.setStyleSheet(_fromUtf8("color: #e3e4e5;"))
        self.battery_status.setObjectName(_fromUtf8("battery_status"))
        self.horizontalLayout.addWidget(self.battery_status)
        self.label_10 = QtGui.QLabel(PyLogin)
        self.label_10.setGeometry(QtCore.QRect(40, 250, 401, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(570, 620, 231, 81))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.play_sound = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_2)
        self.play_sound.setMinimumSize(QtCore.QSize(51, 51))
        self.play_sound.setMaximumSize(QtCore.QSize(51, 51))
        self.play_sound.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/PLaySound.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_sound.setIcon(icon1)
        self.play_sound.setIconSize(QtCore.QSize(40, 40))
        self.play_sound.setObjectName(_fromUtf8("play_sound"))
        self.horizontalLayout_2.addWidget(self.play_sound)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(171, 51))
        self.label_7.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.goback = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_5)
        self.goback.setMinimumSize(QtCore.QSize(51, 51))
        self.goback.setMaximumSize(QtCore.QSize(51, 51))
        self.goback.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.goback.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/back-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goback.setIcon(icon2)
        self.goback.setIconSize(QtCore.QSize(40, 40))
        self.goback.setObjectName(_fromUtf8("goback"))
        self.horizontalLayout_6.addWidget(self.goback)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setMinimumSize(QtCore.QSize(111, 51))
        self.label_5.setMaximumSize(QtCore.QSize(111, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato Heavy"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(360, 620, 201, 81))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lost = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_7)
        self.lost.setMinimumSize(QtCore.QSize(51, 51))
        self.lost.setMaximumSize(QtCore.QSize(51, 51))
        self.lost.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/lost_mode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lost.setIcon(icon3)
        self.lost.setIconSize(QtCore.QSize(40, 40))
        self.lost.setObjectName(_fromUtf8("lost"))
        self.horizontalLayout_3.addWidget(self.lost)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_13.setMinimumSize(QtCore.QSize(141, 51))
        self.label_13.setMaximumSize(QtCore.QSize(141, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(PyLogin)
        self.label_14.setGeometry(QtCore.QRect(50, 610, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato Heavy"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(PyLogin)
        self.label_15.setGeometry(QtCore.QRect(80, 670, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato Heavy"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.line = QtGui.QFrame(PyLogin)
        self.line.setGeometry(QtCore.QRect(560, 630, 20, 71))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_3 = QtGui.QFrame(PyLogin)
        self.line_3.setGeometry(QtCore.QRect(30, 230, 961, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(PyLogin)
        self.line_4.setGeometry(QtCore.QRect(30, 560, 961, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_16 = QtGui.QLabel(PyLogin)
        self.label_16.setGeometry(QtCore.QRect(440, 260, 351, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(790, 240, 191, 80))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.automation = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_8)
        self.automation.setMinimumSize(QtCore.QSize(51, 51))
        self.automation.setMaximumSize(QtCore.QSize(51, 51))
        self.automation.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/automation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.automation.setIcon(icon4)
        self.automation.setIconSize(QtCore.QSize(40, 40))
        self.automation.setObjectName(_fromUtf8("automation"))
        self.horizontalLayout_8.addWidget(self.automation)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_17.setMinimumSize(QtCore.QSize(131, 51))
        self.label_17.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_8.addWidget(self.label_17)
        self.line_2 = QtGui.QFrame(PyLogin)
        self.line_2.setGeometry(QtCore.QRect(420, 260, 20, 41))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lost_phonne = QtGui.QLineEdit(PyLogin)
        self.lost_phonne.setGeometry(QtCore.QRect(170, 670, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lost_phonne.setFont(font)
        self.lost_phonne.setStyleSheet(_fromUtf8("color: #626065;"))
        self.lost_phonne.setObjectName(_fromUtf8("lost_phonne"))
        self.lost_message = QtGui.QTextEdit(PyLogin)
        self.lost_message.setGeometry(QtCore.QRect(170, 610, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lost_message.setFont(font)
        self.lost_message.setStyleSheet(_fromUtf8("color: #626065;"))
        self.lost_message.setObjectName(_fromUtf8("lost_message"))
        self.line_5 = QtGui.QFrame(PyLogin)
        self.line_5.setGeometry(QtCore.QRect(800, 630, 20, 71))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(PyLogin)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(810, 620, 171, 80))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.map = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_6)
        self.map.setMinimumSize(QtCore.QSize(51, 51))
        self.map.setMaximumSize(QtCore.QSize(51, 51))
        self.map.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.map.setIcon(icon5)
        self.map.setIconSize(QtCore.QSize(40, 40))
        self.map.setObjectName(_fromUtf8("map"))
        self.horizontalLayout_7.addWidget(self.map)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_9.setMinimumSize(QtCore.QSize(91, 51))
        self.label_9.setMaximumSize(QtCore.QSize(91, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.download_label = QtGui.QLabel(PyLogin)
        self.download_label.setGeometry(QtCore.QRect(290, 410, 225, 51))
        self.download_label.setMinimumSize(QtCore.QSize(225, 51))
        self.download_label.setMaximumSize(QtCore.QSize(225, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato Heavy"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.download_label.setFont(font)
        self.download_label.setObjectName(_fromUtf8("download_label"))
        self.download = QtGui.QCommandLinkButton(PyLogin)
        self.download.setGeometry(QtCore.QRect(230, 400, 51, 51))
        self.download.setMinimumSize(QtCore.QSize(51, 51))
        self.download.setMaximumSize(QtCore.QSize(51, 51))
        self.download.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon6)
        self.download.setIconSize(QtCore.QSize(40, 40))
        self.download.setObjectName(_fromUtf8("download"))
        self.delete_button = QtGui.QCommandLinkButton(PyLogin)
        self.delete_button.setGeometry(QtCore.QRect(540, 400, 51, 59))
        self.delete_button.setMinimumSize(QtCore.QSize(51, 59))
        self.delete_button.setMaximumSize(QtCore.QSize(51, 59))
        self.delete_button.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon7)
        self.delete_button.setIconSize(QtCore.QSize(40, 40))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.delete_label = QtGui.QLabel(PyLogin)
        self.delete_label.setGeometry(QtCore.QRect(590, 410, 191, 41))
        self.delete_label.setMinimumSize(QtCore.QSize(191, 41))
        self.delete_label.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato Heavy"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.delete_label.setFont(font)
        self.delete_label.setObjectName(_fromUtf8("delete_label"))
        self.show_result = QtGui.QTextEdit(PyLogin)
        self.show_result.setGeometry(QtCore.QRect(40, 330, 611, 211))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI Semibold"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.show_result.setFont(font)
        self.show_result.setStyleSheet(_fromUtf8("color: #626065;"))
        self.show_result.setObjectName(_fromUtf8("show_result"))

        self.retranslateUi(PyLogin)
        QtCore.QMetaObject.connectSlotsByName(PyLogin)

    def retranslateUi(self, PyLogin):
        PyLogin.setWindowTitle(_translate("PyLogin", "PyCloud", None))
        self.label.setText(
            _translate("PyLogin", "<html><head/><body><p><img src=\":/Images/login_bg.png\"/></p></body></html>", None))
        self.label_2.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size:25px\">User : </span></p></body></html>",
                                        None))
        self.label_3.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Phone :</span></p></body></html>",
                                        None))
        self.user_name.setText(_translate("PyLogin",
                                          "<html><head/><body><p><span style=\"color:#b9b9b9; font-size:30px\"></span></p></body></html>",
                                          None))
        self.phone_name.setText(_translate("PyLogin",
                                           "<html><head/><body><p><span style=\"color:#b9b9b9; font-size:30px\"></span></p></body></html>",
                                           None))
        self.label_4.setText(
            _translate("PyLogin", "<html><head/><body><p><img src=\":/Images/phone.png\"/></p></body></html>", None))
        self.label_6.setText(
            _translate("PyLogin", "<html><head/><body><p><img src=\":/Images/battery.png\"/></p></body></html>", None))
        self.label_8.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" font-size:25px; color:#ececec;\">Battery Status :</span></p></body></html>",
                                        None))
        self.battery_status.setText(_translate("PyLogin",
                                               "<html><head/><body><p><span style=\"color:#b9b9b9; font-size:30px\"></span></p></body></html>",
                                               None))
        self.label_10.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 40px\">PyCloud Downloader</span></p></body></html>",
                                         None))
        self.label_7.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Alert iPhone</span></p></body></html>",
                                        None))
        self.label_5.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size: 15pt\">Go Back</span></p></body></html>",
                                        None))
        self.label_13.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Lost Mode</span></p></body></html>",
                                         None))
        self.label_14.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Message </span></p></body></html>",
                                         None))
        self.label_15.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Phone </span></p></body></html>",
                                         None))
        self.label_16.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 23px\">Automate PyCLoud Downloader : </span></p></body></html>",
                                         None))
        self.label_17.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Automate</span></p></body></html>",
                                         None))
        self.label_9.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size: 27px\">Locate</span></p></body></html>",
                                        None))
        self.download_label.setText(_translate("PyLogin",
                                               "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Download Photos</span></p></body></html>",
                                               None))
        self.delete_label.setText(_translate("PyLogin",
                                             "<html><head/><body><p><span style=\" color:#ececec; font-size: 25px\">Delete Photos</span></p></body></html>",
                                             None))


import PyCloudResource

if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    PyLogin = QtGui.QWidget()
    ui = Ui_PyLogin()
    ui.setupUi(PyLogin)
    PyLogin.show()
    sys.exit(app.exec_())
