# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Log.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_PyLogin(object):
    def setupUi(self, PyLogin):
        PyLogin.setObjectName(_fromUtf8("PyLogin"))
        PyLogin.resize(1025, 738)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Graphics/Icon/PyCloud-icon.png")), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        PyLogin.setWindowIcon(icon)
        self.label = QtGui.QLabel(PyLogin)
        self.label.setGeometry(QtCore.QRect(0, 0, 1031, 741))
        self.label.setObjectName(_fromUtf8("label"))
        self.goback = QtGui.QCommandLinkButton(PyLogin)
        self.goback.setGeometry(QtCore.QRect(20, 20, 171, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.goback.setFont(font)
        self.goback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goback.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.goback.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/back-arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goback.setIcon(icon1)
        self.goback.setIconSize(QtCore.QSize(40, 40))
        self.goback.setObjectName(_fromUtf8("goback"))
        self.line = QtGui.QFrame(PyLogin)
        self.line.setGeometry(QtCore.QRect(30, 230, 961, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(PyLogin)
        self.line_2.setGeometry(QtCore.QRect(30, 560, 971, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_2 = QtGui.QLabel(PyLogin)
        self.label_2.setGeometry(QtCore.QRect(-200, -240, 351, 451))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(PyLogin)
        self.label_3.setGeometry(QtCore.QRect(520, 90, 71, 131))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(PyLogin)
        self.label_4.setGeometry(QtCore.QRect(190, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_8 = QtGui.QLabel(PyLogin)
        self.label_8.setGeometry(QtCore.QRect(190, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.user_name = QtGui.QLabel(PyLogin)
        self.user_name.setGeometry(QtCore.QRect(290, 120, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.user_name.setFont(font)
        self.user_name.setText(_fromUtf8(""))
        self.user_name.setObjectName(_fromUtf8("user_name"))
        self.phone_name = QtGui.QLabel(PyLogin)
        self.phone_name.setGeometry(QtCore.QRect(290, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.phone_name.setFont(font)
        self.phone_name.setText(_fromUtf8(""))
        self.phone_name.setObjectName(_fromUtf8("phone_name"))
        self.label_5 = QtGui.QLabel(PyLogin)
        self.label_5.setGeometry(QtCore.QRect(640, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.battery_status = QtGui.QLabel(PyLogin)
        self.battery_status.setGeometry(QtCore.QRect(830, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battery_status.setFont(font)
        self.battery_status.setObjectName(_fromUtf8("battery_status"))
        self.label_6 = QtGui.QLabel(PyLogin)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 381, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_3 = QtGui.QFrame(PyLogin)
        self.line_3.setGeometry(QtCore.QRect(400, 260, 20, 41))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_7 = QtGui.QLabel(PyLogin)
        self.label_7.setGeometry(QtCore.QRect(420, 250, 381, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.automation = QtGui.QCommandLinkButton(PyLogin)
        self.automation.setGeometry(QtCore.QRect(800, 250, 191, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.automation.setFont(font)
        self.automation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.automation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.automation.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/automation .png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.automation.setIcon(icon2)
        self.automation.setIconSize(QtCore.QSize(40, 40))
        self.automation.setObjectName(_fromUtf8("automation"))
        self.show_result = QtGui.QTextEdit(PyLogin)
        self.show_result.setGeometry(QtCore.QRect(30, 320, 641, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.show_result.setFont(font)
        self.show_result.setStyleSheet(_fromUtf8("color:#626065;"))
        self.show_result.setObjectName(_fromUtf8("show_result"))
        self.download = QtGui.QCommandLinkButton(PyLogin)
        self.download.setGeometry(QtCore.QRect(180, 400, 291, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.download.setFont(font)
        self.download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.download.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon3)
        self.download.setIconSize(QtCore.QSize(40, 40))
        self.download.setObjectName(_fromUtf8("download"))
        self.delete_button = QtGui.QCommandLinkButton(PyLogin)
        self.delete_button.setGeometry(QtCore.QRect(570, 400, 291, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.delete_button.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon4)
        self.delete_button.setIconSize(QtCore.QSize(40, 40))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.line_4 = QtGui.QFrame(PyLogin)
        self.line_4.setGeometry(QtCore.QRect(590, 630, 3, 61))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(PyLogin)
        self.line_5.setGeometry(QtCore.QRect(830, 630, 3, 61))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_10 = QtGui.QLabel(PyLogin)
        self.label_10.setGeometry(QtCore.QRect(40, 600, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(PyLogin)
        self.label_11.setGeometry(QtCore.QRect(70, 670, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lost_phonee = QtGui.QLineEdit(PyLogin)
        self.lost_phonee.setGeometry(QtCore.QRect(180, 670, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lost_phonee.setFont(font)
        self.lost_phonee.setStyleSheet(_fromUtf8("color: #626065;"))
        self.lost_phonee.setObjectName(_fromUtf8("lost_phonee"))
        self.lost_message = QtGui.QTextEdit(PyLogin)
        self.lost_message.setGeometry(QtCore.QRect(180, 606, 191, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Yu Gothic UI"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lost_message.setFont(font)
        self.lost_message.setStyleSheet(_fromUtf8("color: #626065;"))
        self.lost_message.setObjectName(_fromUtf8("lost_message"))
        self.lost = QtGui.QCommandLinkButton(PyLogin)
        self.lost.setGeometry(QtCore.QRect(380, 630, 201, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lost.setFont(font)
        self.lost.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lost.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lost.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/lost_mode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lost.setIcon(icon5)
        self.lost.setIconSize(QtCore.QSize(40, 40))
        self.lost.setObjectName(_fromUtf8("lost"))
        self.play_sound = QtGui.QCommandLinkButton(PyLogin)
        self.play_sound.setGeometry(QtCore.QRect(600, 630, 221, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.play_sound.setFont(font)
        self.play_sound.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_sound.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.play_sound.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/PLaySound.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_sound.setIcon(icon6)
        self.play_sound.setIconSize(QtCore.QSize(40, 40))
        self.play_sound.setObjectName(_fromUtf8("play_sound"))
        self.map = QtGui.QCommandLinkButton(PyLogin)
        self.map.setGeometry(QtCore.QRect(850, 630, 151, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.map.setFont(font)
        self.map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.map.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.map.setStyleSheet(_fromUtf8("color: #ececec;"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Images/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.map.setIcon(icon7)
        self.map.setIconSize(QtCore.QSize(40, 40))
        self.map.setObjectName(_fromUtf8("map"))
        self.label.raise_()
        self.label_2.raise_()
        self.goback.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.user_name.raise_()
        self.phone_name.raise_()
        self.label_5.raise_()
        self.battery_status.raise_()
        self.label_6.raise_()
        self.line_3.raise_()
        self.label_7.raise_()
        self.automation.raise_()
        self.show_result.raise_()
        self.download.raise_()
        self.delete_button.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.lost_phonee.raise_()
        self.lost_message.raise_()
        self.lost.raise_()
        self.play_sound.raise_()
        self.map.raise_()

        self.retranslateUi(PyLogin)
        QtCore.QMetaObject.connectSlotsByName(PyLogin)

    def retranslateUi(self, PyLogin):
        PyLogin.setWindowTitle(_translate("PyLogin", "PyCloud - User", None))
        self.label.setText(
            _translate("PyLogin", "<html><head/><body><p><img src=\":/Images/login_bg.png\"/></p></body></html>", None))
        self.goback.setToolTip(_translate("PyLogin", "Go Back", None))
        self.goback.setText(_translate("PyLogin", "Go Back", None))
        self.label_2.setText(_translate("PyLogin",
                                        "<html><head/><body><p><img src=\":/Images/Graphics/GUI Images/phone.png\"/></p></body></html>",
                                        None))
        self.label_3.setText(
            _translate("PyLogin", "<html><head/><body><p><img src=\":/Images/battery.png\"/></p></body></html>", None))
        self.label_4.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size:25px\">User :</span></p></body></html>\'",
                                        None))
        self.label_8.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size:25px\">Phone :</span></p></body></html>\'",
                                        None))
        self.label_5.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" color:#ececec; font-size:25px\">Battery Status :</span></p></body></html>\'",
                                        None))
        self.battery_status.setText(_translate("PyLogin",
                                               "<html><head/><body><p><span style=\" color:#ececec; font-size:25px\"></span></p></body></html>",
                                               None))
        self.label_6.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" font-size:23pt; color:#f7f9fb;\">PyCloud Downloader</span></p></body></html>",
                                        None))
        self.label_7.setText(_translate("PyLogin",
                                        "<html><head/><body><p><span style=\" font-size:15pt; color:#f7f9fb;\">Automate PyCloud Downloader :</span></p></body></html>",
                                        None))
        self.automation.setToolTip(_translate("PyLogin", "Automation", None))
        self.automation.setText(_translate("PyLogin", "Automate", None))
        self.show_result.setHtml(_translate("PyLogin",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Yu Gothic UI\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
                                            "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#626065;\"><br /></span></p></body></html>",
                                            None))
        self.download.setToolTip(_translate("PyLogin", "Download", None))
        self.download.setText(_translate("PyLogin", "Download Photos", None))
        self.delete_button.setToolTip(_translate("PyLogin", "Delete", None))
        self.delete_button.setText(_translate("PyLogin", "  Delete Photos", None))
        self.label_10.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" font-size:17pt; color:#f7f9fb;\">Message :</span></p></body></html>",
                                         None))
        self.label_11.setText(_translate("PyLogin",
                                         "<html><head/><body><p><span style=\" font-size:17pt; color:#f7f9fb;\">Phone :</span></p></body></html>",
                                         None))
        self.lost.setToolTip(_translate("PyLogin", "Lost Mode", None))
        self.lost.setText(_translate("PyLogin", "Lost Mode", None))
        self.play_sound.setToolTip(_translate("PyLogin", "Alert iPhone", None))
        self.play_sound.setText(_translate("PyLogin", "Alert iPhone", None))
        self.map.setToolTip(_translate("PyLogin", "Locate iPhone", None))
        self.map.setText(_translate("PyLogin", "Locate", None))


import PyCloudResource

if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    PyLogin = QtGui.QWidget()
    ui = Ui_PyLogin()
    ui.setupUi(PyLogin)
    PyLogin.show()
    sys.exit(app.exec_())
